"""Backend-independent browser capability interface."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .models import (
    BrowserAction,
    BrowserObservation,
    BrowserSession,
    BrowserTab,
    NavigationResult,
    Screenshot,
)


class BrowserProvider(Protocol):
    async def start_session(self, persistent_state_path: str | None = None) -> BrowserSession: ...

    async def close_session(self, session_id: UUID) -> None: ...

    async def new_tab(self, session_id: UUID) -> BrowserTab: ...

    async def close_tab(self, tab_id: UUID) -> None: ...

    async def navigate(self, tab_id: UUID, url: str) -> NavigationResult: ...

    async def go_back(self, tab_id: UUID) -> NavigationResult: ...

    async def go_forward(self, tab_id: UUID) -> NavigationResult: ...

    async def reload(self, tab_id: UUID) -> NavigationResult: ...

    async def observe(self, tab_id: UUID) -> BrowserObservation: ...

    async def click(self, tab_id: UUID, element_id: str) -> BrowserObservation: ...

    async def fill(self, tab_id: UUID, element_id: str, value: str, sensitive: bool = False) -> BrowserObservation: ...

    async def select_option(self, tab_id: UUID, element_id: str, option: str) -> BrowserObservation: ...

    async def press_key(self, tab_id: UUID, element_id: str, key: str) -> BrowserObservation: ...

    async def extract_text(self, tab_id: UUID) -> object: ...

    async def extract_links(self, tab_id: UUID) -> object: ...

    async def wait(self, tab_id: UUID, seconds: float = 0.0) -> BrowserObservation: ...

    async def download(self, tab_id: UUID, selector: str | None = None) -> object: ...

    async def screenshot(self, tab_id: UUID) -> Screenshot: ...

    async def get_current_url(self, tab_id: UUID) -> str: ...

    async def login(self, service: str) -> None: ...

    async def use_authenticated_session(self, service: str) -> None: ...


class BrowserActionExecutor(Protocol):
    async def execute_async(self, action: BrowserAction) -> object: ...
